server:
  host: 0.0.0.0
  port: 8080

auth:
  user: admin
  password: admin
  secret_key: change-me-in-production-please
  access_token_expiry: 86400000000000  # 24 hours in nanoseconds
  refresh_token_expiry: 2592000000000000  # 30 days in nanoseconds
  nonce_expiry: 120000000000  # 2 minutes in nanoseconds

database:
  path: ha-mi.db

home_assistant:
  url: http://localhost:8123
  token: ""  # Put your Home Assistant long-lived access token here 